config/routes.rb
Rails.application.routes.draw do
  resources :number_requests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/number_request.rb
class NumberRequest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/number_requests_controller.rb
class NumberRequestsController < ApplicationController
  require 'net/http'
  before_action :set_number_request, only: %i[ show edit update destroy ]

  # GET /number_requests or /number_requests.json
  def index
    @number_requests = NumberRequest.all
  end

  # GET /number_requests/1 or /number_requests/1.json
  def show
  end

  # GET /number_requests/new
  def new
    @number_request = NumberRequest.new
  end

  # GET /number_requests/1/edit
  def edit
  end

  # POST /number_requests or /number_requests.json
  def create
    @number_request = NumberRequest.new(number_request_params)

    response = make_api_request(@number_request.input)

    @number_request.response = response

    respond_to do |format|
      if @number_request.save
        format.html { redirect_to number_request_url(@number_request), notice: "Number request was successfully created." }
        format.json { render :show, status: :created, location: @number_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @number_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /number_requests/1 or /number_requests/1.json
  def update
    respond_to do |format|
      if @number_request.update(number_request_params)
        format.html { redirect_to number_request_url(@number_request), notice: "Number request was successfully updated." }
        format.json { render :show, status: :ok, location: @number_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @number_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /number_requests/1 or /number_requests/1.json
  def destroy
    @number_request.destroy!

    respond_to do |format|
      format.html { redirect_to number_requests_url, notice: "Number request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number_request
      @number_request = NumberRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def number_request_params
      params.require(:number_request).permit(:input, :response)
    end

    def make_api_request(input)
      uri = URI("http://localhost:3000/api/v1/numbers/")
      numbers = input.split(',').map(&:strip)
      if numbers.length == 1
        uri.path += "single/#{numbers.first}"
        response = Net::HTTP.get(uri)
      else
        uri.path += "batch"
        response = Net::HTTP.post_form(uri, 'numbers[]' => numbers).body
      end
      response
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/number_requests_helper.rb
module NumberRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Client</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/number_requests/_form.html.erb
<%= form_with(model: number_request) do |form| %>
  <% if number_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(number_request.errors.count, "error") %> prohibited this number_request from being saved:</h2>

      <ul>
        <% number_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :input, style: "display: block" %>
    <%= form.text_field :input %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/number_requests/_number_request.html.erb
<div id="<%= dom_id number_request %>">
  <p>
    <strong>Input:</strong>
    <%= number_request.input %>
  </p>

  <p>
    <strong>Response:</strong>
    <%= number_request.response %>
  </p>

</div>

app/views/number_requests/edit.html.erb
<h1>Editing number request</h1>

<%= render "form", number_request: @number_request %>

<br>

<div>
  <%= link_to "Show this number request", @number_request %> |
  <%= link_to "Back to number requests", number_requests_path %>
</div>

app/views/number_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Number requests</h1>

<div id="number_requests">
  <% @number_requests.each do |number_request| %>
    <%= render number_request %>
    <p>
      <%= link_to "Show this number request", number_request %>
    </p>
  <% end %>
</div>

<%= link_to "New number request", new_number_request_path %>

app/views/number_requests/new.html.erb
<h1>New number request</h1>

<%= render "form", number_request: @number_request %>

<br>

<div>
  <%= link_to "Back to number requests", number_requests_path %>
</div>

app/views/number_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @number_request %>

<div>
  <%= link_to "Edit this number request", edit_number_request_path(@number_request) %> |
  <%= link_to "Back to number requests", number_requests_path %>

  <%= button_to "Destroy this number request", @number_request, method: :delete %>
</div>